apiVersion: v1
kind: Service
metadata:
  labels:
    app: category
  name: category
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: category
  type: NodePort
status:
  loadBalancer: {}
